name: Discord Attachment Poller
on:
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight UTC
  workflow_dispatch:  # Allows manual triggering
jobs:
  poll-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run Discord poller
        run: python discord_poller.py
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Commit state file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
           commit_message: "Update processed messages file"
           branch: ${{ github.head_ref }}
